name: ImagoInk
favicon: null
layout_spectrum: 0.22579
typography_spectrum: 0.49217
title: Libros personalizados
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-2839903-27
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5f3f6'
    - '#ac9992'
    - '#f14933'
    - '#39363d'
    - '#edce41'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
