name: ImagoInk
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49217
title: Libros personalizados
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-2839903-27
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5f3f6'
    - '#ac9992'
    - '#f14933'
    - '#39363d'
    - '#edce41'
  brandStrength: 0.43188693071715534
  lightness: 0.6875
  saturation: 0.4345938835758716
  rhythmicContrast: 0.6191483419388533
purpose: []
